import { Injectable } from '@angular/core';
import { of } from 'rxjs';
import { JobRequisition } from '../models/requisition.model';

@Injectable({ providedIn: 'root' })
export class RequisitionService {

    // Static Mock Data
    private requisitions: JobRequisition[] = [
        {
            id: 'REQ-2024-001',
            title: 'Senior Angular Developer',
            department: 'Engineering',
            location: 'Bangalore, India',
            employmentType: 'Full-time',
            positions: 2,
            priority: 'High',
            description: 'Expert Angular developer for enterprise HRMS platform.',
            skills: ['Angular', 'TypeScript', 'RxJS', 'Material'],
            experienceRange: '5-8 Years',
            education: 'B.Tech / MCA',
            salaryMin: 2000000,
            salaryMax: 3500000,
            hiringManager: 'John Doe',
            recruiter: 'Jane Smith',
            interviewPanel: ['Tech Lead', 'Architect'],
            approver1: 'Director Eng',
            approver2: 'HR VP',
            status: 'Pending Approval',
            timeline: [
                { step: 'Created', approver: 'Jane Smith', date: new Date(), status: 'Completed' },
                { step: 'Manager Approval', approver: 'Director Eng', date: new Date(), status: 'Current' },
                { step: 'HR Approval', approver: 'HR VP', date: new Date(), status: 'Pending' }
            ]
        },
        {
            id: 'REQ-2024-002',
            title: 'Backend Node.js Developer',
            department: 'Engineering',
            location: 'Hyderabad, India',
            employmentType: 'Full-time',
            positions: 3,
            priority: 'Medium',
            description: 'Node.js developer for scalable APIs.',
            skills: ['Node.js', 'Express', 'MySQL'],
            experienceRange: '4-6 Years',
            education: 'B.Tech',
            salaryMin: 1500000,
            salaryMax: 2500000,
            hiringManager: 'Ravi Kumar',
            recruiter: 'Anita Rao',
            interviewPanel: ['Backend Lead'],
            approver1: 'Director Eng',
            approver2: 'HR VP',
            status: 'Approved',
            timeline: []
        },
        {
            id: 'REQ-2024-003',
            title: 'HR Executive',
            department: 'Human Resources',
            location: 'Chennai, India',
            employmentType: 'Full-time',
            positions: 1,
            priority: 'Low',
            description: 'HR operations and employee engagement.',
            skills: ['HR Operations', 'Payroll'],
            experienceRange: '2-4 Years',
            education: 'MBA HR',
            salaryMin: 600000,
            salaryMax: 900000,
            hiringManager: 'Meena Iyer',
            recruiter: 'Suresh',
            interviewPanel: ['HR Manager'],
            approver1: 'HR Head',
            approver2: 'HR VP',
            status: 'Draft',
            timeline: []
        },
        {
            id: 'REQ-2024-004',
            title: 'QA Automation Engineer',
            department: 'Quality Assurance',
            location: 'Pune, India',
            employmentType: 'Full-time',
            positions: 2,
            priority: 'High',
            description: 'Automation testing for web apps.',
            skills: ['Selenium', 'Cypress', 'JavaScript'],
            experienceRange: '3-5 Years',
            education: 'B.Tech',
            salaryMin: 1200000,
            salaryMax: 2000000,
            hiringManager: 'Amit Shah',
            recruiter: 'Neha',
            interviewPanel: ['QA Lead'],
            approver1: 'Director QA',
            approver2: 'HR VP',
            status: 'Pending Approval',
            timeline: []
        },
        {
            id: 'REQ-2024-005',
            title: 'UI/UX Designer',
            department: 'Design',
            location: 'Remote',
            employmentType: 'Contract',
            positions: 1,
            priority: 'Medium',
            description: 'Design modern HRMS interfaces.',
            skills: ['Figma', 'UX Research'],
            experienceRange: '4-6 Years',
            education: 'Design Degree',
            salaryMin: 1000000,
            salaryMax: 1800000,
            hiringManager: 'Andrew Smith',
            recruiter: 'Jane Smith',
            interviewPanel: ['Design Lead'],
            approver1: 'Product Head',
            approver2: 'HR VP',
            status: 'Approved',
            timeline: []
        },

        // ---- MORE RECORDS ----

        {
            id: 'REQ-2024-006',
            title: 'DevOps Engineer',
            department: 'Engineering',
            location: 'Bangalore, India',
            employmentType: 'Full-time',
            positions: 2,
            priority: 'High',
            description: 'Cloud infrastructure & CI/CD.',
            skills: ['AWS', 'Docker', 'Kubernetes'],
            experienceRange: '5-7 Years',
            education: 'B.Tech',
            salaryMin: 2200000,
            salaryMax: 3500000,
            hiringManager: 'Vikram Rao',
            recruiter: 'Neha',
            interviewPanel: ['DevOps Lead'],
            approver1: 'CTO',
            approver2: 'HR VP',
            status: 'Pending Approval',
            timeline: []
        },
        {
            id: 'REQ-2024-007',
            title: 'Data Analyst',
            department: 'Analytics',
            location: 'Mumbai, India',
            employmentType: 'Full-time',
            positions: 1,
            priority: 'Medium',
            description: 'Business insights & reporting.',
            skills: ['SQL', 'Power BI'],
            experienceRange: '3-5 Years',
            education: 'B.Sc / MCA',
            salaryMin: 900000,
            salaryMax: 1500000,
            hiringManager: 'Rahul Jain',
            recruiter: 'Anita Rao',
            interviewPanel: ['Analytics Lead'],
            approver1: 'Business Head',
            approver2: 'HR VP',
            status: 'Approved',
            timeline: []
        },
        {
            id: 'REQ-2024-008',
            title: 'Technical Recruiter',
            department: 'Recruitment',
            location: 'Bangalore, India',
            employmentType: 'Full-time',
            positions: 2,
            priority: 'High',
            description: 'End-to-end IT hiring.',
            skills: ['ATS', 'Sourcing'],
            experienceRange: '2-4 Years',
            education: 'MBA',
            salaryMin: 700000,
            salaryMax: 1200000,
            hiringManager: 'HR Manager',
            recruiter: 'Self',
            interviewPanel: ['Recruitment Lead'],
            approver1: 'HR Head',
            approver2: 'HR VP',
            status: 'Draft',
            timeline: []
        },
        {
            id: 'REQ-2024-009',
            title: 'Java Developer',
            department: 'Engineering',
            location: 'Noida, India',
            employmentType: 'Full-time',
            positions: 3,
            priority: 'Medium',
            description: 'Spring Boot microservices.',
            skills: ['Java', 'Spring Boot', 'MySQL'],
            experienceRange: '4-7 Years',
            education: 'B.Tech',
            salaryMin: 1600000,
            salaryMax: 2800000,
            hiringManager: 'Sanjay Verma',
            recruiter: 'Neha',
            interviewPanel: ['Tech Lead'],
            approver1: 'Director Eng',
            approver2: 'HR VP',
            status: 'Approved',
            timeline: []
        },
        {
            id: 'REQ-2024-010',
            title: 'Product Manager',
            department: 'Product',
            location: 'Bangalore, India',
            employmentType: 'Full-time',
            positions: 1,
            priority: 'High',
            description: 'Own HRMS product roadmap.',
            skills: ['Agile', 'Stakeholder Mgmt'],
            experienceRange: '6-9 Years',
            education: 'MBA',
            salaryMin: 2500000,
            salaryMax: 4000000,
            hiringManager: 'CEO',
            recruiter: 'Jane Smith',
            interviewPanel: ['Leadership Team'],
            approver1: 'CEO',
            approver2: 'HR VP',
            status: 'Pending Approval',
            timeline: []
        },
    ];


    getRequisitions() {
        return of(this.requisitions);
    }

    getRequisitionById(id: string) {
        return of(this.requisitions.find(r => r.id === id));
    }
}