import { Component, inject, OnInit, signal } from '@angular/core';
import { FormBuilder, FormGroup, FormsModule, ReactiveFormsModule, Validators } from '@angular/forms';
import { MATERIAL } from '../../../../shared/material/materials';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { API_ENDPOINTS } from '../../../../core/config/api-endpoints';
import { CommonService } from '../../../../core/services/common.service';
import { ApiClient } from '../../../../core/services/api-client.service';
import { Subject, takeUntil } from 'rxjs';

@Component({
  selector: 'app-employee-onboarding',
  imports: [MATERIAL, FormsModule, CommonModule, ReactiveFormsModule, RouterModule],
  templateUrl: './employee-onboarding.html',
  styleUrl: './employee-onboarding.scss',
})
export class EmployeeOnboarding implements OnInit {
  private _formBuilder = inject(FormBuilder);
  private _commonService = inject(CommonService);
  private _httpClient = inject(ApiClient)
  // Enum Options based on your Schema
  // Dynamic Lookup Options
  roles = ['EMPLOYEE', 'MANAGER', 'HR_ADMIN', 'SUPER_ADMIN'];
  relations = ['SPOUSE', 'PARENT', 'SIBLING', 'FRIEND'];
  maritalStatuses = ['SINGLE', 'MARRIED'];

  genderList: any[] = [];
  employmentTypeList: any[] = [];
  workModeList: any[] = [];
  statusList: any[] = [];
  departmentList = signal<any[]>([]);
  designationList = signal<any[]>([]);
  employeesList = signal<any[]>([]);

  // Main Form Group
  onboardingForm = this._formBuilder.group({

    // STEP 1: Professional (Profile + User + Job)
    professional: this._formBuilder.group({
      firstName: ['', Validators.required],
      lastName: [''],
      email: ['', [Validators.required, Validators.email]],
      role: ['EMPLOYEE', Validators.required],
      employeeCode: [''],
      joiningDate: [new Date(), Validators.required],
      department: [''],
      designation: [''],
      manager: [''],
      workMode: ['WFO'],
      employmentType: ['FULL_TIME'],
      location: [''],
      reported_to: [''],
      status: ['ACTIVE']
    }),

    // STEP 2: Personal (Personal + Emergency)
    personal: this._formBuilder.group({
      dob: [''],
      gender: ['MALE'],
      maritalStatus: ['SINGLE'],
      nationality: [''],
      bloodGroup: [''],
      personalEmail: ['', Validators.email],
      contactNumber: [''],
      // Emergency Contact Nested Group
      emergencyName: [''],
      emergencyRelation: [''],
      emergencyPhone: [''],
      address: ['']
    }),

    // STEP 3: Finance & Docs (Bank + Documents)
    finance: this._formBuilder.group({
      bankName: [''],
      accountNumber: [''],
      ifscCode: [''],
      isSalaryAccount: [true],
      pan: [''],
      aadhar: [''],
      // File tracking
      aadharFile: [null],
      panFile: [null]
    })
  });
  destroy$ = new Subject<void>();

  ngOnInit(): void {
    this.loadLookupData();
    this.loadDepartments();
    this.loadEmployees();
    this.getAutoGeneratedId();
    this.getEmployeeDetails();
    // this.loadDesignations();
  }

  async loadLookupData() {
    const categories = API_ENDPOINTS.lookup.categories;
    const lookupData = await this._commonService.getBulkLookupData([
      categories.gender,
      categories.employee_type,
      categories.work_mode,
      categories.status
    ]);

    if (lookupData) {
      this.genderList = lookupData[categories.gender] || [];
      this.employmentTypeList = lookupData[categories.employee_type] || [];
      this.workModeList = lookupData[categories.work_mode] || [];
      this.statusList = lookupData[categories.status] || [];
    }
  }


  // Getter for easy access in template
  get proForm() { return this.onboardingForm.get('professional') as FormGroup; }
  get persForm() { return this.onboardingForm.get('personal') as FormGroup; }
  get finForm() { return this.onboardingForm.get('finance') as FormGroup; }

  // File Upload Handler (Mock)
  onFileSelected(event: any, controlName: string) {
    const file = event.target.files[0];
    if (file) {
      this.finForm.patchValue({ [controlName]: file.name });
    }
  }

  onSubmit() {
    if (this.onboardingForm.invalid) {
      return;
    }
    this._httpClient.post(API_ENDPOINTS.employee.create, this.onboardingForm.value).subscribe({
      next: (res) => {
        console.log(res);
      },
      error: (err) => {
        console.log(err);
      }
    })
  }

  loadDepartments() {
    this._httpClient.get(API_ENDPOINTS.dropdown.departments).pipe(takeUntil(this.destroy$)).subscribe({
      next: (_res: any) => {
        if (_res?.data && Array.isArray(_res.data)) {
          this.departmentList.set(_res.data);
        }
      },
      error: (_err: any) => {
        console.error('Error loading departments:', _err);
      }
    });
  }

  loadDesignations(deptId: string) {
    const payload = {
      departmentId: deptId
    }
    this._httpClient.post(API_ENDPOINTS.dropdown.designations, payload).pipe(takeUntil(this.destroy$)).subscribe({
      next: (_res: any) => {
        if (_res?.data && Array.isArray(_res.data)) {
          this.designationList.set(_res.data);
        }
      },
      error: (_err: any) => {
        console.error('Error loading designations:', _err);
      }
    });
  }

  loadEmployees() {
    this._httpClient.get(API_ENDPOINTS.dropdown.employees).pipe(takeUntil(this.destroy$)).subscribe({
      next: (_res: any) => {
        if (_res?.sts === 200 && Array.isArray(_res.data)) {
          this.employeesList.set(_res.data);
        }
      },
      error: (_err: any) => {
        console.error('Error loading employees:', _err);
      }
    });
  }

  getAutoGeneratedId() {
    this._httpClient.get(API_ENDPOINTS.employee.auto_generated_emp_id).pipe(takeUntil(this.destroy$)).subscribe({
      next: (_res: any) => {
        const emp_code = _res.data.emp_code;
        this.onboardingForm
          .get('professional.employeeCode')
          ?.patchValue(emp_code);
      },
      error: (_err: any) => {
        console.error('Error loading employees:', _err);
      }
    });
  }

  getEmployeeDetails() {
    const payload = {
      page: 1,
      limit: 10,
      search_key: '',
      id: '69848fc3b834505ef3a85583'
    }
    this._httpClient.post(API_ENDPOINTS.employee.get, payload).pipe(takeUntil(this.destroy$)).subscribe({
      next: (res: any) => {

      },
      error: (err) => {
        console.log(err);
      }
    })
  }
}
